### PR TITLE
Wording clarifications and simplifications.

### PR DESCRIPTION
**Pull request by gcharters**
Hopefully this helps, but feel free to discard or discuss things you disagree with.

### CODE REVIEW

**Comment by yeekangc** [comment]
@Kubik42 @sishida, can you please review?  Please work with @gcharters to clarify if necessary.

We do want to make the topic as straightforward to understand as possible.  And, what we have currently did stumble Graham.

Tagging @evelinec for awareness.

**Comment by sishida** [comment]
I'm working on some Nov. beta work and other doc. at the moment. What is the "due date" for reviewing this item? Thanks!

**Comment by Kubik42** [comment]
I think these changes are a great improvement. I added a bit of my own stuff on top to clarify some other parts of the guide. I'll merge this PR and open up a new one with my changes, @sishida can you review that one instead?

**Comment by sishida** [comment]
@Kubik42: Sure, I can review the other PR. Could you please send me a link to it when you create it? Thank you! :)

**Pull request merged**
